# Generated by Django 2.2 on 2019-04-25 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('postid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('hashtag', models.TextField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencer.Influencer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
