# Generated by Django 2.1.5 on 2019-05-01 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addid', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pageid', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='adds',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbadds.Page'),
        ),
    ]
